AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 120

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/BlockDelimiters:
  Exclude:
    - spec/**/*_spec.rb
