AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/BlockDelimiters:
  Exclude:
    - spec/**/*_spec.rb
